# Generated by Django 5.0.3 on 2024-03-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pagamentoAluguel',
            new_name='Pagamento',
        ),
    ]
